// Corruption Perception Index 2024
// Source: Transparency International via Wikipedia
// URL: https://www.transparency.org/en/cpi/2024
// Wikipedia: https://en.wikipedia.org/wiki/Corruption_Perceptions_Index
// Download date: 2025-12-27
// Scale: 0 (highly corrupt) to 100 (very clean)
// Total countries: 180

var cpiData = {
    "Afghanistan": 17,
    "Albania": 42,
    "Algeria": 34,
    "Angola": 32,
    "Argentina": 37,
    "Armenia": 47,
    "Australia": 77,
    "Austria": 67,
    "Azerbaijan": 22,
    "Bahamas": 65,
    "Bahrain": 53,
    "Bangladesh": 23,
    "Barbados": 68,
    "Belarus": 33,
    "Belgium": 69,
    "Benin": 45,
    "Bhutan": 72,
    "Bolivia": 28,
    "Bosnia and Herzegovina": 33,
    "Botswana": 57,
    "Brazil": 34,
    "Bulgaria": 43,
    "Burkina Faso": 41,
    "Burundi": 17,
    "Cambodia": 21,
    "Cameroon": 26,
    "Canada": 75,
    "Cabo Verde": 62,
    "Central African Republic": 24,
    "Chad": 21,
    "Chile": 63,
    "China": 43,
    "Colombia": 39,
    "Comoros": 21,
    "Congo": 23,
    "Costa Rica": 58,
    "Croatia": 47,
    "Cuba": 41,
    "Cyprus": 56,
    "Czech Republic": 56,
    "Democratic Republic of the Congo": 20,
    "Denmark": 90,
    "Djibouti": 31,
    "Dominica": 60,
    "Dominican Republic": 36,
    "Ecuador": 32,
    "Egypt": 30,
    "El Salvador": 30,
    "Equatorial Guinea": 13,
    "Eritrea": 13,
    "Estonia": 76,
    "Eswatini": 27,
    "Ethiopia": 37,
    "Fiji": 55,
    "Finland": 88,
    "France": 67,
    "Gabon": 27,
    "Gambia": 38,
    "Georgia": 53,
    "Germany": 75,
    "Ghana": 42,
    "Greece": 49,
    "Grenada": 56,
    "Guatemala": 25,
    "Guinea": 28,
    "Guinea-Bissau": 21,
    "Guyana": 39,
    "Haiti": 16,
    "Honduras": 22,
    "Hong Kong": 74,
    "Hungary": 41,
    "Iceland": 77,
    "India": 38,
    "Indonesia": 37,
    "Iran": 23,
    "Iraq": 26,
    "Ireland": 77,
    "Israel": 64,
    "Italy": 54,
    "Ivory Coast": 45,
    "Jamaica": 44,
    "Japan": 71,
    "Jordan": 49,
    "Kazakhstan": 41,
    "Kenya": 32,
    "Kosovo": 44,
    "Kuwait": 46,
    "Kyrgyzstan": 25,
    "Laos": 33,
    "Latvia": 59,
    "Lebanon": 22,
    "Lesotho": 37,
    "Liberia": 27,
    "Libya": 13,
    "Lithuania": 63,
    "Luxembourg": 81,
    "Madagascar": 26,
    "Malawi": 34,
    "Malaysia": 50,
    "Maldives": 38,
    "Mali": 27,
    "Malta": 46,
    "Mauritania": 30,
    "Mauritius": 51,
    "Mexico": 26,
    "Moldova": 43,
    "Mongolia": 33,
    "Montenegro": 46,
    "Morocco": 37,
    "Mozambique": 25,
    "Myanmar": 16,
    "Namibia": 49,
    "Nepal": 34,
    "Netherlands": 78,
    "New Zealand": 83,
    "Nicaragua": 14,
    "Niger": 34,
    "Nigeria": 26,
    "North Korea": 15,
    "North Macedonia": 40,
    "Norway": 81,
    "Oman": 55,
    "Pakistan": 27,
    "Panama": 33,
    "Papua New Guinea": 31,
    "Paraguay": 24,
    "Peru": 31,
    "Philippines": 33,
    "Poland": 53,
    "Portugal": 57,
    "Qatar": 59,
    "Romania": 46,
    "Russia": 22,
    "Rwanda": 57,
    "Saint Lucia": 59,
    "Saint Vincent and the Grenadines": 63,
    "Saudi Arabia": 59,
    "Senegal": 45,
    "Serbia": 35,
    "Seychelles": 72,
    "Sierra Leone": 33,
    "Singapore": 84,
    "Slovakia": 49,
    "Slovenia": 60,
    "Solomon Islands": 43,
    "Somalia": 9,
    "South Africa": 41,
    "South Korea": 64,
    "South Sudan": 8,
    "Spain": 56,
    "Sri Lanka": 32,
    "Sudan": 15,
    "Suriname": 40,
    "Sweden": 80,
    "Switzerland": 81,
    "Syria": 12,
    "São Tomé and Príncipe": 45,
    "Taiwan": 67,
    "Tajikistan": 19,
    "Tanzania": 41,
    "Thailand": 34,
    "Timor-Leste": 44,
    "Togo": 32,
    "Trinidad and Tobago": 41,
    "Tunisia": 39,
    "Turkey": 34,
    "Turkmenistan": 17,
    "Uganda": 26,
    "Ukraine": 35,
    "United Arab Emirates": 68,
    "United Kingdom": 71,
    "United States of America": 65,
    "Uruguay": 76,
    "Uzbekistan": 32,
    "Vanuatu": 50,
    "Venezuela": 10,
    "Vietnam": 40,
    "Yemen": 13,
    "Zambia": 39,
    "Zimbabwe": 21
}
