module.exports = {
    "Norway": {
        "rank": 1,
        "id": "Norway",
        "score": "*9.93*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 9.64,
        "politicalparticipation": 10,
        "politicalculture": 10,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "Iceland": {
        "rank": 2,
        "id": "Iceland",
        "score": "*9.58*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 8.89,
        "politicalculture": 10,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "Sweden": {
        "rank": 3,
        "id": "Sweden",
        "score": "*9.45*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 9.64,
        "politicalparticipation": 8.33,
        "politicalculture": 10,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "New Zealand": {
        "rank": 4,
        "id": "New Zealand",
        "score": "*9.26*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 8.89,
        "politicalculture": 8.13,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "Denmark": {
        "rank": 5,
        "id": "Denmark",
        "score": "*9.11*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 8.33,
        "politicalculture": 9.38,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Switzerland": {
        "rank": 6,
        "id": "Switzerland",
        "score": "*9.09*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 7.78,
        "politicalculture": 9.38,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Canada": {
        "rank": 7,
        "id": "Canada",
        "score": "*9.08*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 7.78,
        "politicalculture": 8.75,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "Finland": {
        "rank": 8,
        "id": "Finland",
        "score": "*9.03*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 8.93,
        "politicalparticipation": 7.78,
        "politicalculture": 8.75,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "Australia": {
        "rank": 9,
        "id": "Australia",
        "score": "*9.01*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 8.93,
        "politicalparticipation": 7.78,
        "politicalculture": 8.75,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "Netherlands": {
        "rank": 10,
        "id": "Netherlands",
        "score": "*8.92*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 8.57,
        "politicalparticipation": 8.89,
        "politicalculture": 8.13,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Luxembourg": {
        "rank": 11,
        "id": "Luxembourg",
        "score": "*8.88*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 9.29,
        "politicalparticipation": 6.67,
        "politicalculture": 8.75,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "Ireland": {
        "rank": 12,
        "id": "Ireland",
        "score": "*8.85*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.5,
        "politicalparticipation": 7.78,
        "politicalculture": 9.38,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "Germany": {
        "rank": 13,
        "id": "Germany",
        "score": "*8.64*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 8.57,
        "politicalparticipation": 7.78,
        "politicalculture": 8.13,
        "civilliberties": 9.12,
        "category": "*Full democracy*"
    },
    "Austria": {
        "rank": 14,
        "id": "Austria",
        "score": "*8.54*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 8.33,
        "politicalculture": 7.5,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Malta": {
        "rank": 15,
        "id": "Malta",
        "score": "*8.39*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 8.21,
        "politicalparticipation": 6.11,
        "politicalculture": 8.75,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "United Kingdom": {
        "rank": 16,
        "id": "United Kingdom",
        "score": "*8.31*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 6.67,
        "politicalculture": 8.75,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Spain": {
        "rank": 17,
        "id": "Spain",
        "score": "*8.30*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 7.22,
        "politicalculture": 8.13,
        "civilliberties": 9.41,
        "category": "*Full democracy*"
    },
    "Mauritius": {
        "rank": 18,
        "id": "Mauritius",
        "score": "*8.28*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 8.21,
        "politicalparticipation": 5.56,
        "politicalculture": 8.75,
        "civilliberties": 9.71,
        "category": "*Full democracy*"
    },
    "Uruguay": {
        "rank": 19,
        "id": "Uruguay",
        "score": "*8.17*",
        "electoralProcessandPluralism": 10,
        "functioningOfgovernment": 8.93,
        "politicalparticipation": 4.44,
        "politicalculture": 7.5,
        "civilliberties": 10,
        "category": "*Full democracy*"
    },
    "United States": {
        "rank": 20,
        "id": "United States",
        "score": "*8.05*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 7.5,
        "politicalparticipation": 7.22,
        "politicalculture": 8.13,
        "civilliberties": 8.24,
        "category": "*Full democracy*"
    },
    "Italy": {
        "rank": 21,
        "id": "Italy",
        "score": "*7.98*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 6.43,
        "politicalparticipation": 7.22,
        "politicalculture": 8.13,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "South Korea": {
        "rank": 22,
        "id": "South Korea",
        "score": "*7.97*",
        "electoralProcessandPluralism": 8.75,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 7.22,
        "politicalculture": 7.5,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "Japan": {
        "rank": 23,
        "id": "Japan",
        "score": "*7.96*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 8.21,
        "politicalparticipation": 6.11,
        "politicalculture": 7.5,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "Costa Rica": {
        "rank": 23,
        "id": "Costa Rica",
        "score": "*7.96*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.5,
        "politicalparticipation": 6.11,
        "politicalculture": 6.88,
        "civilliberties": 9.71,
        "category": "*Flawed democracy*"
    },
    "Czech Republic": {
        "rank": 25,
        "id": "Czech Republic",
        "score": "*7.94*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 6.67,
        "politicalculture": 6.88,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Belgium": {
        "rank": 26,
        "id": "Belgium",
        "score": "*7.93*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 8.21,
        "politicalparticipation": 5.56,
        "politicalculture": 6.88,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "France": {
        "rank": 27,
        "id": "France",
        "score": "*7.92*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 7.78,
        "politicalculture": 6.25,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "Botswana": {
        "rank": 28,
        "id": "Botswana",
        "score": "*7.87*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 6.11,
        "politicalculture": 7.5,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Estonia": {
        "rank": 29,
        "id": "Estonia",
        "score": "*7.85*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 6.11,
        "politicalculture": 6.88,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "Chile": {
        "rank": 30,
        "id": "Chile",
        "score": "*7.84*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 8.57,
        "politicalparticipation": 4.44,
        "politicalculture": 6.88,
        "civilliberties": 9.71,
        "category": "*Flawed democracy*"
    },
    "Republic of China (Taiwan)": {
        "rank": 31,
        "id": "Republic of China (Taiwan)",
        "score": "*7.83*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Cape Verde": {
        "rank": 32,
        "id": "Cape Verde",
        "score": "*7.81*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 6.67,
        "politicalculture": 6.25,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Portugal": {
        "rank": 33,
        "id": "Portugal",
        "score": "*7.79*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 6.43,
        "politicalparticipation": 6.67,
        "politicalculture": 6.88,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Israel": {
        "rank": 34,
        "id": "Israel",
        "score": "*7.77*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 8.89,
        "politicalculture": 7.5,
        "civilliberties": 6.18,
        "category": "*Flawed democracy*"
    },
    "India": {
        "rank": 35,
        "id": "India",
        "score": "*7.74*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 7.22,
        "politicalculture": 5.63,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Slovenia": {
        "rank": 36,
        "id": "Slovenia",
        "score": "*7.57*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "South Africa": {
        "rank": 37,
        "id": "South Africa",
        "score": "*7.56*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 8.21,
        "politicalparticipation": 8.33,
        "politicalculture": 5,
        "civilliberties": 7.94,
        "category": "*Flawed democracy*"
    },
    "Lithuania": {
        "rank": 38,
        "id": "Lithuania",
        "score": "*7.54*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 6.11,
        "politicalculture": 6.25,
        "civilliberties": 9.71,
        "category": "*Flawed democracy*"
    },
    "Cyprus": {
        "rank": 39,
        "id": "Cyprus",
        "score": "*7.53*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.43,
        "politicalparticipation": 6.67,
        "politicalculture": 6.25,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Greece": {
        "rank": 40,
        "id": "Greece",
        "score": "*7.45*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 6.67,
        "politicalculture": 6.25,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Jamaica": {
        "rank": 41,
        "id": "Jamaica",
        "score": "*7.39*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.79,
        "politicalparticipation": 5,
        "politicalculture": 6.88,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Latvia": {
        "rank": 42,
        "id": "Latvia",
        "score": "*7.37*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5.56,
        "politicalculture": 6.88,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Slovakia": {
        "rank": 43,
        "id": "Slovakia",
        "score": "*7.29*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.5,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "Timor-Leste": {
        "rank": 44,
        "id": "Timor-Leste",
        "score": "*7.24*",
        "electoralProcessandPluralism": 8.67,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 5.56,
        "politicalculture": 6.88,
        "civilliberties": 7.94,
        "category": "*Flawed democracy*"
    },
    "Panama": {
        "rank": 45,
        "id": "Panama",
        "score": "*7.19*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 6.43,
        "politicalparticipation": 6.11,
        "politicalculture": 5,
        "civilliberties": 8.82,
        "category": "*Flawed democracy*"
    },
    "Bulgaria": {
        "rank": 46,
        "id": "Bulgaria",
        "score": "*7.14*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 7.22,
        "politicalculture": 5,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Trinidad and Tobago": {
        "rank": 47,
        "id": "Trinidad and Tobago",
        "score": "*7.10*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Poland": {
        "rank": 48,
        "id": "Poland",
        "score": "*7.09*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 6.67,
        "politicalculture": 4.38,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Indonesia": {
        "rank": 49,
        "id": "Indonesia",
        "score": "*7.03*",
        "electoralProcessandPluralism": 7.75,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 6.67,
        "politicalculture": 6.25,
        "civilliberties": 7.35,
        "category": "*Flawed democracy*"
    },
    "Argentina": {
        "rank": 50,
        "id": "Argentina",
        "score": "*7.02*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 5,
        "politicalparticipation": 6.11,
        "politicalculture": 6.88,
        "civilliberties": 7.94,
        "category": "*Flawed democracy*"
    },
    "Brazil": {
        "rank": 51,
        "id": "Brazil",
        "score": "*6.96*",
        "electoralProcessandPluralism": 9.58,
        "functioningOfgovernment": 6.79,
        "politicalparticipation": 5.56,
        "politicalculture": 3.75,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Croatia": {
        "rank": 52,
        "id": "Croatia",
        "score": "*6.93*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 5.56,
        "politicalculture": 5.63,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Ghana": {
        "rank": 53,
        "id": "Ghana",
        "score": "*6.86*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 6.67,
        "politicalculture": 6.25,
        "civilliberties": 7.35,
        "category": "*Flawed democracy*"
    },
    "Philippines": {
        "rank": 54,
        "id": "Philippines",
        "score": "*6.84*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 6.67,
        "politicalculture": 4.38,
        "civilliberties": 9.12,
        "category": "*Flawed democracy*"
    },
    "Hungary": {
        "rank": 54,
        "id": "Hungary",
        "score": "*6.84*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 4.44,
        "politicalculture": 6.88,
        "civilliberties": 7.65,
        "category": "*Flawed democracy*"
    },
    "Suriname": {
        "rank": 56,
        "id": "Suriname",
        "score": "*6.77*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.43,
        "politicalparticipation": 5,
        "politicalculture": 5,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Tunisia": {
        "rank": 57,
        "id": "Tunisia",
        "score": "*6.72*",
        "electoralProcessandPluralism": 7,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 7.78,
        "politicalculture": 6.88,
        "civilliberties": 5.88,
        "category": "*Flawed democracy*"
    },
    "Serbia": {
        "rank": 58,
        "id": "Serbia",
        "score": "*6.71*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 6.67,
        "politicalculture": 5,
        "civilliberties": 7.35,
        "category": "*Flawed democracy*"
    },
    "Romania": {
        "rank": 59,
        "id": "Romania",
        "score": "*6.68*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5,
        "politicalculture": 5,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "Dominican Republic": {
        "rank": 60,
        "id": "Dominican Republic",
        "score": "*6.67*",
        "electoralProcessandPluralism": 8.75,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5,
        "politicalculture": 6.25,
        "civilliberties": 7.65,
        "category": "*Flawed democracy*"
    },
    "El Salvador": {
        "rank": 61,
        "id": "El Salvador",
        "score": "*6.64*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 4.44,
        "politicalculture": 5,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "Mongolia": {
        "rank": 62,
        "id": "Mongolia",
        "score": "*6.62*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5,
        "politicalculture": 5,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Colombia": {
        "rank": 62,
        "id": "Colombia",
        "score": "*6.62*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 7.14,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "Lesotho": {
        "rank": 64,
        "id": "Lesotho",
        "score": "*6.59*",
        "electoralProcessandPluralism": 8.25,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 7.06,
        "category": "*Flawed democracy*"
    },
    "Peru": {
        "rank": 65,
        "id": "Peru",
        "score": "*6.58*",
        "electoralProcessandPluralism": 9.17,
        "functioningOfgovernment": 5,
        "politicalparticipation": 6.11,
        "politicalculture": 4.38,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Mexico": {
        "rank": 66,
        "id": "Mexico",
        "score": "*6.55*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 7.22,
        "politicalculture": 4.38,
        "civilliberties": 6.76,
        "category": "*Flawed democracy*"
    },
    "Hong Kong": {
        "rank": 67,
        "id": "Hong Kong",
        "score": "*6.50*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5.56,
        "politicalculture": 7.5,
        "civilliberties": 9.41,
        "category": "*Flawed democracy*"
    },
    "Malaysia": {
        "rank": 68,
        "id": "Malaysia",
        "score": "*6.43*",
        "electoralProcessandPluralism": 6.92,
        "functioningOfgovernment": 7.86,
        "politicalparticipation": 5.56,
        "politicalculture": 6.25,
        "civilliberties": 5.59,
        "category": "*Flawed democracy*"
    },
    "Sri Lanka": {
        "rank": 69,
        "id": "Sri Lanka",
        "score": "*6.42*",
        "electoralProcessandPluralism": 7.83,
        "functioningOfgovernment": 6.79,
        "politicalparticipation": 5,
        "politicalculture": 6.88,
        "civilliberties": 5.59,
        "category": "*Flawed democracy*"
    },
    "Moldova": {
        "rank": 70,
        "id": "Moldova",
        "score": "*6.35*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 6.67,
        "politicalculture": 4.38,
        "civilliberties": 8.53,
        "category": "*Flawed democracy*"
    },
    "Paraguay": {
        "rank": 71,
        "id": "Paraguay",
        "score": "*6.33*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Namibia": {
        "rank": 72,
        "id": "Namibia",
        "score": "*6.31*",
        "electoralProcessandPluralism": 5.67,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 8.24,
        "category": "*Flawed democracy*"
    },
    "Zambia": {
        "rank": 73,
        "id": "Zambia",
        "score": "*6.28*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 3.89,
        "politicalculture": 6.88,
        "civilliberties": 7.35,
        "category": "*Flawed democracy*"
    },
    "Singapore": {
        "rank": 74,
        "id": "Singapore",
        "score": "*6.14*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 7.5,
        "politicalparticipation": 5.56,
        "politicalculture": 6.25,
        "civilliberties": 7.06,
        "category": "*Flawed democracy*"
    },
    "Senegal": {
        "rank": 75,
        "id": "Senegal",
        "score": "*6.08*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 4.44,
        "politicalculture": 5.63,
        "civilliberties": 7.06,
        "category": "*Flawed democracy*"
    },
    "Guyana": {
        "rank": 76,
        "id": "Guyana",
        "score": "*6.05*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 5.56,
        "politicalculture": 4.38,
        "civilliberties": 7.06,
        "category": "*Flawed democracy*"
    },
    "Papua New Guinea": {
        "rank": 77,
        "id": "Papua New Guinea",
        "score": "*6.03*",
        "electoralProcessandPluralism": 6.92,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 3.89,
        "politicalculture": 5.63,
        "civilliberties": 7.65,
        "category": "*Flawed democracy*"
    },
    "Macedonia": {
        "rank": 78,
        "id": "Macedonia",
        "score": "*6.02*",
        "electoralProcessandPluralism": 7.33,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 6.11,
        "politicalculture": 4.38,
        "civilliberties": 7.65,
        "category": "*Flawed democracy*"
    },
    "Montenegro": {
        "rank": 79,
        "id": "Montenegro",
        "score": "*6.01*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 7.06,
        "category": "*Flawed democracy*"
    },
    "Guatemala": {
        "rank": 80,
        "id": "Guatemala",
        "score": "*5.92*",
        "electoralProcessandPluralism": 7.92,
        "functioningOfgovernment": 6.07,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 7.35,
        "category": "*Hybrid regime*"
    },
    "Albania": {
        "rank": 81,
        "id": "Albania",
        "score": "*5.91*",
        "electoralProcessandPluralism": 7,
        "functioningOfgovernment": 4.36,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 7.65,
        "category": "*Hybrid regime*"
    },
    "Georgia": {
        "rank": 82,
        "id": "Georgia",
        "score": "*5.88*",
        "electoralProcessandPluralism": 8.67,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 5.88,
        "category": "*Hybrid regime*"
    },
    "Ecuador": {
        "rank": 83,
        "id": "Ecuador",
        "score": "*5.87*",
        "electoralProcessandPluralism": 8.25,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 7.06,
        "category": "*Hybrid regime*"
    },
    "Honduras": {
        "rank": 84,
        "id": "Honduras",
        "score": "*5.84*",
        "electoralProcessandPluralism": 8.75,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 6.47,
        "category": "*Hybrid regime*"
    },
    "Bolivia": {
        "rank": 85,
        "id": "Bolivia",
        "score": "*5.75*",
        "electoralProcessandPluralism": 7,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 5,
        "politicalculture": 3.75,
        "civilliberties": 7.65,
        "category": "*Hybrid regime*"
    },
    "Bangladesh": {
        "rank": 86,
        "id": "Bangladesh",
        "score": "*5.73*",
        "electoralProcessandPluralism": 7.42,
        "functioningOfgovernment": 5.07,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 6.76,
        "category": "*Hybrid regime*"
    },
    "Benin": {
        "rank": 87,
        "id": "Benin",
        "score": "*5.72*",
        "electoralProcessandPluralism": 6.92,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 4.44,
        "politicalculture": 5.63,
        "civilliberties": 5.88,
        "category": "*Hybrid regime*"
    },
    "Ukraine": {
        "rank": 88,
        "id": "Ukraine",
        "score": "*5.70*",
        "electoralProcessandPluralism": 5.83,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 6.67,
        "politicalculture": 5,
        "civilliberties": 7.06,
        "category": "*Hybrid regime*"
    },
    "Mali": {
        "rank": 88,
        "id": "Mali",
        "score": "*5.70*",
        "electoralProcessandPluralism": 7.42,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 4.44,
        "politicalculture": 6.25,
        "civilliberties": 6.47,
        "category": "*Hybrid regime*"
    },
    "Fiji": {
        "rank": 90,
        "id": "Fiji",
        "score": "*5.69*",
        "electoralProcessandPluralism": 4.58,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 5.88,
        "category": "*Hybrid regime*"
    },
    "Tanzania": {
        "rank": 91,
        "id": "Tanzania",
        "score": "*5.58*",
        "electoralProcessandPluralism": 7,
        "functioningOfgovernment": 5,
        "politicalparticipation": 5,
        "politicalculture": 5.63,
        "civilliberties": 5.29,
        "category": "*Hybrid regime*"
    },
    "Malawi": {
        "rank": 92,
        "id": "Malawi",
        "score": "*5.55*",
        "electoralProcessandPluralism": 6.58,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 4.44,
        "politicalculture": 6.25,
        "civilliberties": 6.18,
        "category": "*Hybrid regime*"
    },
    "Kyrgyzstan": {
        "rank": 93,
        "id": "Kyrgyzstan",
        "score": "*5.33*",
        "electoralProcessandPluralism": 7.83,
        "functioningOfgovernment": 3.29,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 5,
        "category": "*Hybrid regime*"
    },
    "Kenya": {
        "rank": 93,
        "id": "Kenya",
        "score": "*5.33*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 5,
        "politicalparticipation": 6.67,
        "politicalculture": 5.63,
        "civilliberties": 5,
        "category": "*Hybrid regime*"
    },
    "Nicaragua": {
        "rank": 95,
        "id": "Nicaragua",
        "score": "*5.26*",
        "electoralProcessandPluralism": 6.17,
        "functioningOfgovernment": 3.29,
        "politicalparticipation": 4.44,
        "politicalculture": 5.63,
        "civilliberties": 6.76,
        "category": "*Hybrid regime*"
    },
    "Uganda": {
        "rank": 96,
        "id": "Uganda",
        "score": "*5.22*",
        "electoralProcessandPluralism": 5.67,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 4.44,
        "politicalculture": 6.25,
        "civilliberties": 6.18,
        "category": "*Hybrid regime*"
    },
    "Turkey": {
        "rank": 97,
        "id": "Turkey",
        "score": "*5.12*",
        "electoralProcessandPluralism": 6.67,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 5,
        "politicalculture": 5.63,
        "civilliberties": 2.94,
        "category": "*Hybrid regime*"
    },
    "Thailand": {
        "rank": 98,
        "id": "Thailand",
        "score": "*5.09*",
        "electoralProcessandPluralism": 4.5,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 6.47,
        "category": "*Hybrid regime*"
    },
    "Venezuela": {
        "rank": 99,
        "id": "Venezuela",
        "score": "*5.00*",
        "electoralProcessandPluralism": 6.08,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 5.59,
        "category": "*Hybrid regime*"
    },
    "Liberia": {
        "rank": 100,
        "id": "Liberia",
        "score": "*4.95*",
        "electoralProcessandPluralism": 7.83,
        "functioningOfgovernment": 0.79,
        "politicalparticipation": 5.56,
        "politicalculture": 5,
        "civilliberties": 5.59,
        "category": "*Hybrid regime*"
    },
    "Bhutan": {
        "rank": 101,
        "id": "Bhutan",
        "score": "*4.93*",
        "electoralProcessandPluralism": 8.33,
        "functioningOfgovernment": 5.36,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 3.82,
        "category": "*Hybrid regime*"
    },
    "Lebanon": {
        "rank": 102,
        "id": "Lebanon",
        "score": "*4.86*",
        "electoralProcessandPluralism": 4.42,
        "functioningOfgovernment": 2.14,
        "politicalparticipation": 7.78,
        "politicalculture": 4.38,
        "civilliberties": 5.59,
        "category": "*Hybrid regime*"
    },
    "Madagascar": {
        "rank": 103,
        "id": "Madagascar",
        "score": "*4.85*",
        "electoralProcessandPluralism": 5.5,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 5.56,
        "politicalculture": 5.63,
        "civilliberties": 4.71,
        "category": "*Hybrid regime*"
    },
    "Bosnia and Herzegovina": {
        "rank": 104,
        "id": "Bosnia and Herzegovina",
        "score": "*4.83*",
        "electoralProcessandPluralism": 6.5,
        "functioningOfgovernment": 2.93,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 6.47,
        "category": "*Hybrid regime*"
    },
    "Nepal": {
        "rank": 105,
        "id": "Nepal",
        "score": "*4.77*",
        "electoralProcessandPluralism": 3.92,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 4.44,
        "politicalculture": 5.63,
        "civilliberties": 5.59,
        "category": "*Hybrid regime*"
    },
    "Burkina Faso": {
        "rank": 106,
        "id": "Burkina Faso",
        "score": "*4.70*",
        "electoralProcessandPluralism": 4.42,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 4.44,
        "politicalculture": 5.63,
        "civilliberties": 4.71,
        "category": "*Hybrid regime*"
    },
    "Morocco": {
        "rank": 107,
        "id": "Morocco",
        "score": "*4.66*",
        "electoralProcessandPluralism": 4.75,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 3.89,
        "politicalculture": 5.63,
        "civilliberties": 4.41,
        "category": "*Hybrid regime*"
    },
    "Nigeria": {
        "rank": 108,
        "id": "Nigeria",
        "score": "*4.62*",
        "electoralProcessandPluralism": 6.08,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 3.33,
        "politicalculture": 5,
        "civilliberties": 4.41,
        "category": "*Hybrid regime*"
    },
    "Mozambique": {
        "rank": 109,
        "id": "Mozambique",
        "score": "*4.60*",
        "electoralProcessandPluralism": 4.42,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 5.56,
        "politicalculture": 5.63,
        "civilliberties": 3.82,
        "category": "*Hybrid regime*"
    },
    "Palestine": {
        "rank": 110,
        "id": "Palestine",
        "score": "*4.57*",
        "electoralProcessandPluralism": 4.75,
        "functioningOfgovernment": 2.14,
        "politicalparticipation": 7.78,
        "politicalculture": 4.38,
        "civilliberties": 3.82,
        "category": "*Hybrid regime*"
    },
    "Sierra Leone": {
        "rank": 111,
        "id": "Sierra Leone",
        "score": "*4.55*",
        "electoralProcessandPluralism": 6.58,
        "functioningOfgovernment": 1.86,
        "politicalparticipation": 2.78,
        "politicalculture": 6.25,
        "civilliberties": 5.29,
        "category": "*Hybrid regime*"
    },
    "Pakistan": {
        "rank": 112,
        "id": "Pakistan",
        "score": "*4.40*",
        "electoralProcessandPluralism": 6,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 2.78,
        "politicalculture": 2.5,
        "civilliberties": 5,
        "category": "*Hybrid regime*"
    },
    "Cambodia": {
        "rank": 113,
        "id": "Cambodia",
        "score": "*4.27*",
        "electoralProcessandPluralism": 3.17,
        "functioningOfgovernment": 5.71,
        "politicalparticipation": 3.33,
        "politicalculture": 5,
        "civilliberties": 4.12,
        "category": "*Hybrid regime*"
    },
    "Myanmar": {
        "rank": 114,
        "id": "Myanmar",
        "score": "*4.14*",
        "electoralProcessandPluralism": 3.17,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 4.44,
        "politicalculture": 6.88,
        "civilliberties": 2.65,
        "category": "*Hybrid regime*"
    },
    "Iraq": {
        "rank": 115,
        "id": "Iraq",
        "score": "*4.08*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 0.07,
        "politicalparticipation": 7.22,
        "politicalculture": 4.38,
        "civilliberties": 4.41,
        "category": "*Hybrid regime*"
    },
    "Armenia": {
        "rank": 116,
        "id": "Armenia",
        "score": "*4.00*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 4.44,
        "politicalculture": 2.5,
        "civilliberties": 5.88,
        "category": "*Hybrid regime*"
    },
    "Mauritania": {
        "rank": 117,
        "id": "Mauritania",
        "score": "*3.96*",
        "electoralProcessandPluralism": 3,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 5,
        "politicalculture": 3.13,
        "civilliberties": 4.41,
        "category": "*Authoritarian*"
    },
    "Algeria": {
        "rank": 118,
        "id": "Algeria",
        "score": "*3.95*",
        "electoralProcessandPluralism": 3,
        "functioningOfgovernment": 2.21,
        "politicalparticipation": 3.89,
        "politicalculture": 6.25,
        "civilliberties": 4.41,
        "category": "*Authoritarian*"
    },
    "Haiti": {
        "rank": 119,
        "id": "Haiti",
        "score": "*3.94*",
        "electoralProcessandPluralism": 4.75,
        "functioningOfgovernment": 2.21,
        "politicalparticipation": 2.22,
        "politicalculture": 3.75,
        "civilliberties": 6.76,
        "category": "*Authoritarian*"
    },
    "Jordan": {
        "rank": 120,
        "id": "Jordan",
        "score": "*3.86*",
        "electoralProcessandPluralism": 3.58,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 3.53,
        "category": "*Authoritarian*"
    },
    "Kuwait": {
        "rank": 121,
        "id": "Kuwait",
        "score": "*3.85*",
        "electoralProcessandPluralism": 3.17,
        "functioningOfgovernment": 4.29,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 3.53,
        "category": "*Authoritarian*"
    },
    "Niger": {
        "rank": 121,
        "id": "Niger",
        "score": "*3.85*",
        "electoralProcessandPluralism": 6.25,
        "functioningOfgovernment": 1.14,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 4.71,
        "category": "*Authoritarian*"
    },
    "Ethiopia": {
        "rank": 123,
        "id": "Ethiopia",
        "score": "*3.83*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 6.11,
        "politicalculture": 5.63,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Gabon": {
        "rank": 124,
        "id": "Gabon",
        "score": "*3.76*",
        "electoralProcessandPluralism": 3,
        "functioningOfgovernment": 2.21,
        "politicalparticipation": 4.44,
        "politicalculture": 5,
        "civilliberties": 4.12,
        "category": "*Authoritarian*"
    },
    "Comoros": {
        "rank": 125,
        "id": "Comoros",
        "score": "*3.71*",
        "electoralProcessandPluralism": 4.33,
        "functioningOfgovernment": 2.21,
        "politicalparticipation": 4.44,
        "politicalculture": 3.75,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Cameroon": {
        "rank": 126,
        "id": "Cameroon",
        "score": "*3.66*",
        "electoralProcessandPluralism": 2,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 3.89,
        "politicalculture": 5,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Belarus": {
        "rank": 127,
        "id": "Belarus",
        "score": "*3.62*",
        "electoralProcessandPluralism": 1.75,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 3.89,
        "politicalculture": 6.25,
        "civilliberties": 2.65,
        "category": "*Authoritarian*"
    },
    "Vietnam": {
        "rank": 128,
        "id": "Vietnam",
        "score": "*3.53*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 3.89,
        "politicalculture": 6.88,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Cuba": {
        "rank": 129,
        "id": "Cuba",
        "score": "*3.52*",
        "electoralProcessandPluralism": 1.75,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 3.89,
        "politicalculture": 4.38,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Togo": {
        "rank": 130,
        "id": "Togo",
        "score": "*3.41*",
        "electoralProcessandPluralism": 4,
        "functioningOfgovernment": 1.14,
        "politicalparticipation": 2.78,
        "politicalculture": 5,
        "civilliberties": 4.12,
        "category": "*Authoritarian*"
    },
    "Angola": {
        "rank": 131,
        "id": "Angola",
        "score": "*3.35*",
        "electoralProcessandPluralism": 0.92,
        "functioningOfgovernment": 3.21,
        "politicalparticipation": 5,
        "politicalculture": 4.38,
        "civilliberties": 3.24,
        "category": "*Authoritarian*"
    },
    "Ivory Coast": {
        "rank": 132,
        "id": "Ivory Coast",
        "score": "*3.31*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.21,
        "politicalparticipation": 3.89,
        "politicalculture": 5.63,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Russia": {
        "rank": 132,
        "id": "Russia",
        "score": "*3.31*",
        "electoralProcessandPluralism": 2.67,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 5,
        "politicalculture": 2.5,
        "civilliberties": 3.53,
        "category": "*Authoritarian*"
    },
    "Egypt": {
        "rank": 134,
        "id": "Egypt",
        "score": "*3.18*",
        "electoralProcessandPluralism": 3,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 3.33,
        "politicalculture": 3.75,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Qatar": {
        "rank": 134,
        "id": "Qatar",
        "score": "*3.18*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 2.22,
        "politicalculture": 5.63,
        "civilliberties": 4.12,
        "category": "*Authoritarian*"
    },
    "Guinea": {
        "rank": 136,
        "id": "Guinea",
        "score": "*3.14*",
        "electoralProcessandPluralism": 3.5,
        "functioningOfgovernment": 0.43,
        "politicalparticipation": 4.44,
        "politicalculture": 4.38,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "China": {
        "rank": 136,
        "id": "People's Republic of China",
        "score": "*3.14*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 3.33,
        "politicalculture": 6.25,
        "civilliberties": 1.47,
        "category": "*Authoritarian*"
    },
    "People's Republic of China": {
        "rank": 136,
        "id": "People's Republic of China",
        "score": "*3.14*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 4.64,
        "politicalparticipation": 3.33,
        "politicalculture": 6.25,
        "civilliberties": 1.47,
        "category": "*Authoritarian*"
    },
    "Swaziland": {
        "rank": 138,
        "id": "Swaziland",
        "score": "*3.09*",
        "electoralProcessandPluralism": 0.92,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 2.22,
        "politicalculture": 5.63,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Rwanda": {
        "rank": 139,
        "id": "Rwanda",
        "score": "*3.07*",
        "electoralProcessandPluralism": 0.83,
        "functioningOfgovernment": 5,
        "politicalparticipation": 2.22,
        "politicalculture": 4.38,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Kazakhstan": {
        "rank": 140,
        "id": "Kazakhstan",
        "score": "*3.06*",
        "electoralProcessandPluralism": 0.5,
        "functioningOfgovernment": 2.14,
        "politicalparticipation": 4.44,
        "politicalculture": 4.38,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Zimbabwe": {
        "rank": 141,
        "id": "Zimbabwe",
        "score": "*3.05*",
        "electoralProcessandPluralism": 0.5,
        "functioningOfgovernment": 2,
        "politicalparticipation": 3.89,
        "politicalculture": 5.63,
        "civilliberties": 3.24,
        "category": "*Authoritarian*"
    },
    "Oman": {
        "rank": 142,
        "id": "Oman",
        "score": "*3.04*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 4.12,
        "category": "*Authoritarian*"
    },
    "Gambia": {
        "rank": 143,
        "id": "Gambia",
        "score": "*2.97*",
        "electoralProcessandPluralism": 1.33,
        "functioningOfgovernment": 3.93,
        "politicalparticipation": 2.22,
        "politicalculture": 5,
        "civilliberties": 2.35,
        "category": "*Authoritarian*"
    },
    "Republic of the Congo": {
        "rank": 144,
        "id": "Republic of the Congo",
        "score": "*2.91*",
        "electoralProcessandPluralism": 1.67,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 3.33,
        "politicalculture": 3.75,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Djibouti": {
        "rank": 145,
        "id": "Djibouti",
        "score": "*2.90*",
        "electoralProcessandPluralism": 0.42,
        "functioningOfgovernment": 2.5,
        "politicalparticipation": 3.33,
        "politicalculture": 5.63,
        "civilliberties": 2.65,
        "category": "*Authoritarian*"
    },
    "Bahrain": {
        "rank": 146,
        "id": "Bahrain",
        "score": "*2.79*",
        "electoralProcessandPluralism": 1.25,
        "functioningOfgovernment": 3.21,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 2.35,
        "category": "*Authoritarian*"
    },
    "Afghanistan": {
        "rank": 147,
        "id": "Afghanistan",
        "score": "*2.77*",
        "electoralProcessandPluralism": 2.5,
        "functioningOfgovernment": 1.14,
        "politicalparticipation": 3.89,
        "politicalculture": 2.5,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "United Arab Emirates": {
        "rank": 148,
        "id": "United Arab Emirates",
        "score": "*2.75*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.57,
        "politicalparticipation": 2.22,
        "politicalculture": 5,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Azerbaijan": {
        "rank": 149,
        "id": "Azerbaijan",
        "score": "*2.71*",
        "electoralProcessandPluralism": 0.5,
        "functioningOfgovernment": 2.14,
        "politicalparticipation": 3.33,
        "politicalculture": 3.75,
        "civilliberties": 3.82,
        "category": "*Authoritarian*"
    },
    "Burundi": {
        "rank": 150,
        "id": "Burundi",
        "score": "*2.49*",
        "electoralProcessandPluralism": 0.5,
        "functioningOfgovernment": 0.43,
        "politicalparticipation": 3.89,
        "politicalculture": 5,
        "civilliberties": 2.65,
        "category": "*Authoritarian*"
    },
    "Sudan": {
        "rank": 151,
        "id": "Sudan",
        "score": "*2.37*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 1.79,
        "politicalparticipation": 3.89,
        "politicalculture": 5,
        "civilliberties": 1.18,
        "category": "*Authoritarian*"
    },
    "Eritrea": {
        "rank": 151,
        "id": "Eritrea",
        "score": "*2.37*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 2.14,
        "politicalparticipation": 1.67,
        "politicalculture": 6.88,
        "civilliberties": 1.18,
        "category": "*Authoritarian*"
    },
    "Libya": {
        "rank": 153,
        "id": "Libya",
        "score": "*2.25*",
        "electoralProcessandPluralism": 1,
        "functioningOfgovernment": 0,
        "politicalparticipation": 1.67,
        "politicalculture": 5.63,
        "civilliberties": 2.94,
        "category": "*Authoritarian*"
    },
    "Yemen": {
        "rank": 154,
        "id": "Yemen",
        "score": "*2.24*",
        "electoralProcessandPluralism": 0.5,
        "functioningOfgovernment": 0.36,
        "politicalparticipation": 4.44,
        "politicalculture": 5,
        "civilliberties": 0.88,
        "category": "*Authoritarian*"
    },
    "Laos": {
        "rank": 155,
        "id": "Laos",
        "score": "*2.21*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 3.21,
        "politicalparticipation": 1.67,
        "politicalculture": 5,
        "civilliberties": 1.18,
        "category": "*Authoritarian*"
    },
    "Iran": {
        "rank": 156,
        "id": "Iran",
        "score": "*2.16*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 3.33,
        "politicalculture": 3.13,
        "civilliberties": 1.47,
        "category": "*Authoritarian*"
    },
    "Democratic Republic of the Congo": {
        "rank": 157,
        "id": "Democratic Republic of the Congo",
        "score": "*2.11*",
        "electoralProcessandPluralism": 0.92,
        "functioningOfgovernment": 0.71,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 1.76,
        "category": "*Authoritarian*"
    },
    "Uzbekistan": {
        "rank": 158,
        "id": "Uzbekistan",
        "score": "*1.95*",
        "electoralProcessandPluralism": 0.08,
        "functioningOfgovernment": 1.86,
        "politicalparticipation": 2.22,
        "politicalculture": 5,
        "civilliberties": 0.59,
        "category": "*Authoritarian*"
    },
    "Tajikistan": {
        "rank": 158,
        "id": "Tajikistan",
        "score": "*1.95*",
        "electoralProcessandPluralism": 0.58,
        "functioningOfgovernment": 0.07,
        "politicalparticipation": 1.67,
        "politicalculture": 6.25,
        "civilliberties": 1.18,
        "category": "*Authoritarian*"
    },
    "Guinea-Bissau": {
        "rank": 160,
        "id": "Guinea-Bissau",
        "score": "*1.93*",
        "electoralProcessandPluralism": 1.67,
        "functioningOfgovernment": 0,
        "politicalparticipation": 2.78,
        "politicalculture": 3.13,
        "civilliberties": 2.06,
        "category": "*Authoritarian*"
    },
    "Saudi Arabia": {
        "rank": 160,
        "id": "Saudi Arabia",
        "score": "*1.93*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 2.86,
        "politicalparticipation": 2.22,
        "politicalculture": 3.13,
        "civilliberties": 1.47,
        "category": "*Authoritarian*"
    },
    "Turkmenistan": {
        "rank": 162,
        "id": "Turkmenistan",
        "score": "*1.83*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 0.79,
        "politicalparticipation": 2.78,
        "politicalculture": 5,
        "civilliberties": 0.59,
        "category": "*Authoritarian*"
    },
    "Equatorial Guinea": {
        "rank": 163,
        "id": "Equatorial Guinea",
        "score": "*1.77*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 0.79,
        "politicalparticipation": 2.22,
        "politicalculture": 4.38,
        "civilliberties": 1.47,
        "category": "*Authoritarian*"
    },
    "Central African Republic": {
        "rank": 164,
        "id": "Central African Republic",
        "score": "*1.57*",
        "electoralProcessandPluralism": 1.33,
        "functioningOfgovernment": 0,
        "politicalparticipation": 1.67,
        "politicalculture": 2.5,
        "civilliberties": 2.35,
        "category": "*Authoritarian*"
    },
    "Chad": {
        "rank": 165,
        "id": "Chad",
        "score": "*1.50*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 0,
        "politicalparticipation": 1.11,
        "politicalculture": 3.75,
        "civilliberties": 2.65,
        "category": "*Authoritarian*"
    },
    "Syria": {
        "rank": 166,
        "id": "Syria",
        "score": "*1.43*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 0,
        "politicalparticipation": 2.78,
        "politicalculture": 4.38,
        "civilliberties": 0,
        "category": "*Authoritarian*"
    },
    "North Korea": {
        "rank": 167,
        "id": "North Korea",
        "score": "*1.08*",
        "electoralProcessandPluralism": 0,
        "functioningOfgovernment": 2.5,
        "politicalparticipation": 1.67,
        "politicalculture": 1.25,
        "civilliberties": 0,
        "category": "*Authoritarian*"
    },
    "American Samoa" : {
        "rank": "???",
        "id": "North Korea",
        "score": "0",
        "electoralProcessandPluralism": "???",
        "functioningOfgovernment": "???",
        "politicalparticipation": "???",
        "politicalculture": "???",
        "civilliberties": "???",
        "category": "???"
    },
    "Andorra" : {
        "rank": "???",
        "id": "North Korea",
        "score": "0",
        "electoralProcessandPluralism": "???",
        "functioningOfgovernment": "???",
        "politicalparticipation": "???",
        "politicalculture": "???",
        "civilliberties": "???",
        "category": "???"
    },

}
