// ITUC Global Rights Index 2025
// Source: International Trade Union Confederation
// URL: https://www.ituc-csi.org/ituc-global-rights-index
// PDF: en__global_right_index_2025__final_web.pdf
// Download date: 2025-12-27
// Scale: 1-6 (1 = best, 6 = worst) + 5+ for rights violations due to breakdown of rule of law
// Total countries: 153

var itucData = {
    "Afghanistan": "5+",
    "Albania": "3",
    "Algeria": "5",
    "Angola": "4",
    "Argentina": "4",
    "Armenia": "3",
    "Australia": "2",
    "Austria": "1",
    "Bahamas": "3",
    "Bahrain": "5",
    "Bangladesh": "5",
    "Barbados": "2",
    "Belarus": "5",
    "Belgium": "3",
    "Belize": "3",
    "Benin": "4",
    "Bolivia": "3",
    "Bosnia and Herzegovina": "3",
    "Botswana": "4",
    "Brazil": "4",
    "Bulgaria": "3",
    "Burkina": "4",
    "Burundi": "5+",
    "Cambodia": "5",
    "Cameroon": "4",
    "Canada": "3",
    "Central African Republic": "5+",
    "Chad": "4",
    "Chile": "3",
    "China": "5",
    "Colombia": "5",
    "Congo": "4",
    "Costa Rica": "4",
    "Croatia": "2",
    "Czechia": "2",
    "Côte": "3",
    "Denmark": "1",
    "Djibouti": "4",
    "Dominican Republic": "2",
    "Ecuador": "5",
    "Egypt": "5",
    "El Salvador": "4",
    "Eritrea": "5",
    "Estonia": "2",
    "Eswatini": "5",
    "Ethiopia": "4",
    "Faso": "4",
    "Federation": "5",
    "Fiji": "4",
    "Finland": "2",
    "France": "2",
    "Gabon": "3",
    "Georgia": "4",
    "Germany": "1",
    "Ghana": "2",
    "Greece": "4",
    "Guatemala": "5",
    "Guinea": "4",
    "Guinea-Bissau": "4",
    "Haiti": "5+",
    "Honduras": "5",
    "Hong Kong": "5",
    "Hungary": "4",
    "Iceland": "1",
    "India": "5",
    "Indonesia": "5",
    "Iran": "5",
    "Iraq": "5",
    "Ireland": "1",
    "Israel": "4",
    "Italy": "2",
    "Jamaica": "3",
    "Japan": "2",
    "Jordan": "5",
    "Kazakhstan": "5",
    "Kenya": "4",
    "Korea": "5",
    "Kuwait": "5",
    "Kyrgyzstan": "5",
    "Laos": "5",
    "Latvia": "2",
    "Lebanon": "4",
    "Lesotho": "4",
    "Liberia": "4",
    "Libya": "5+",
    "Lithuania": "2",
    "Madagascar": "4",
    "Malawi": "2",
    "Malaysia": "5",
    "Mali": "4",
    "Mauritania": "5",
    "Mauritius": "3",
    "Mexico": "3",
    "Moldova": "2",
    "Montenegro": "3",
    "Morocco": "3",
    "Mozambique": "3",
    "Myanmar": "5+",
    "Namibia": "3",
    "Nepal": "3",
    "Netherlands": "2",
    "New Zealand": "2",
    "Niger": "4",
    "Nigeria": "5",
    "North Macedonia": "4",
    "Norway": "1",
    "Oman": "3",
    "Pakistan": "5",
    "Palestine": "5+",
    "Panama": "4",
    "Paraguay": "3",
    "Peru": "4",
    "Philippines": "5",
    "Poland": "3",
    "Portugal": "2",
    "Qatar": "5",
    "Republic": "4",
    "Romania": "3",
    "Russian": "5",
    "Rwanda": "3",
    "Saudi Arabia": "5",
    "Senegal": "4",
    "Serbia": "4",
    "Sierra Leone": "4",
    "Singapore": "2",
    "Slovakia": "2",
    "Somalia": "5+",
    "South Africa": "3",
    "South Sudan": "5+",
    "Spain": "2",
    "Sri Lanka": "4",
    "Sudan": "5+",
    "Sweden": "1",
    "Switzerland": "3",
    "Syria": "5+",
    "Taiwan": "2",
    "Tanzania": "4",
    "Thailand": "5",
    "Togo": "3",
    "Trinidad and Tobago": "4",
    "Tunisia": "5",
    "Türkiye": "5",
    "Uganda": "4",
    "Ukraine": "5",
    "United Arab Emirates": "5",
    "United Kingdom": "4",
    "United States of America": "4",
    "Uruguay": "2",
    "Venezuela": "5",
    "Vietnam": "4",
    "Yemen": "5+",
    "Zambia": "4",
    "Zimbabwe": "5"
}
